#include "ReportGenerator.hpp"

#include <fstream>
#include <string>

bool ReportGenerator::generateReport() {

    std::ofstream report("reports/boot_report.txt");

    if (!report.is_open()) {
        return false;
    }

    report << "========================================\n";
    report << "          BOOTSCOPE REPORT\n";
    report << "========================================\n\n";

    report << "This report was generated by BootScope.\n";
    report << "Linux Boot-Time Profiler & Analyzer\n\n";

    report << "========================================\n";
    report << "Report generation completed successfully.\n";
    report << "========================================\n";

    report.close();

    return true;
}